# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\DartCodeII\CodeSet1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CodeSet1(object):
    def setupUi(self, CodeSet1):
        CodeSet1.setObjectName("CodeSet1")
        CodeSet1.resize(693, 320)
        CodeSet1.setMinimumSize(QtCore.QSize(0, 320))
        CodeSet1.setMaximumSize(QtCore.QSize(16777215, 1000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        CodeSet1.setWindowIcon(icon)
        CodeSet1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.metaid = QtWidgets.QLineEdit(CodeSet1)
        self.metaid.setGeometry(QtCore.QRect(431, 50, 133, 20))
        self.metaid.setObjectName("metaid")
        self.label_9 = QtWidgets.QLabel(CodeSet1)
        self.label_9.setGeometry(QtCore.QRect(159, 140, 41, 16))
        self.label_9.setObjectName("label_9")
        self.label_15 = QtWidgets.QLabel(CodeSet1)
        self.label_15.setGeometry(QtCore.QRect(570, 110, 51, 16))
        self.label_15.setObjectName("label_15")
        self.kongid = QtWidgets.QLineEdit(CodeSet1)
        self.kongid.setGeometry(QtCore.QRect(431, 20, 133, 20))
        self.kongid.setObjectName("kongid")
        self.machine = QtWidgets.QLineEdit(CodeSet1)
        self.machine.setGeometry(QtCore.QRect(20, 110, 133, 20))
        self.machine.setObjectName("machine")
        self.mode = QtWidgets.QLineEdit(CodeSet1)
        self.mode.setGeometry(QtCore.QRect(431, 80, 133, 20))
        self.mode.setObjectName("mode")
        self.piname = QtWidgets.QLineEdit(CodeSet1)
        self.piname.setGeometry(QtCore.QRect(20, 50, 133, 20))
        self.piname.setObjectName("piname")
        self.label_8 = QtWidgets.QLabel(CodeSet1)
        self.label_8.setGeometry(QtCore.QRect(159, 80, 31, 16))
        self.label_8.setObjectName("label_8")
        self.label_3 = QtWidgets.QLabel(CodeSet1)
        self.label_3.setGeometry(QtCore.QRect(159, 20, 66, 16))
        self.label_3.setObjectName("label_3")
        self.hole = QtWidgets.QLineEdit(CodeSet1)
        self.hole.setGeometry(QtCore.QRect(431, 110, 133, 20))
        self.hole.setObjectName("hole")
        self.label_5 = QtWidgets.QLabel(CodeSet1)
        self.label_5.setGeometry(QtCore.QRect(159, 50, 66, 16))
        self.label_5.setObjectName("label_5")
        self.count = QtWidgets.QLineEdit(CodeSet1)
        self.count.setGeometry(QtCore.QRect(20, 80, 133, 20))
        self.count.setObjectName("count")
        self.label_12 = QtWidgets.QLabel(CodeSet1)
        self.label_12.setGeometry(QtCore.QRect(570, 18, 42, 16))
        self.label_12.setObjectName("label_12")
        self.nowdate = QtWidgets.QLineEdit(CodeSet1)
        self.nowdate.setGeometry(QtCore.QRect(20, 20, 133, 20))
        self.nowdate.setObjectName("nowdate")
        self.label_13 = QtWidgets.QLabel(CodeSet1)
        self.label_13.setGeometry(QtCore.QRect(570, 50, 31, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(CodeSet1)
        self.label_14.setGeometry(QtCore.QRect(570, 80, 66, 16))
        self.label_14.setObjectName("label_14")
        self.label_19 = QtWidgets.QLabel(CodeSet1)
        self.label_19.setGeometry(QtCore.QRect(20, 230, 261, 21))
        self.label_19.setStyleSheet("color:red;\n"
"font-size:20px;")
        self.label_19.setObjectName("label_19")
        self.optname = QtWidgets.QLineEdit(CodeSet1)
        self.optname.setGeometry(QtCore.QRect(20, 140, 133, 20))
        self.optname.setObjectName("optname")
        self.codeshow = QtWidgets.QLineEdit(CodeSet1)
        self.codeshow.setGeometry(QtCore.QRect(20, 260, 441, 31))
        self.codeshow.setObjectName("codeshow")
        self.cunchu = QtWidgets.QPushButton(CodeSet1)
        self.cunchu.setGeometry(QtCore.QRect(570, 260, 90, 31))
        self.cunchu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cunchu.setStyleSheet("border-radius:5px;\n"
"background-color:#188eee;\n"
"color:#ffffff;\n"
"font-size:16px;")
        self.cunchu.setObjectName("cunchu")
        self.label_18 = QtWidgets.QLabel(CodeSet1)
        self.label_18.setGeometry(QtCore.QRect(160, 110, 31, 16))
        self.label_18.setObjectName("label_18")
        self.label_16 = QtWidgets.QLabel(CodeSet1)
        self.label_16.setGeometry(QtCore.QRect(569, 140, 101, 16))
        self.label_16.setObjectName("label_16")
        self.waterid = QtWidgets.QLineEdit(CodeSet1)
        self.waterid.setGeometry(QtCore.QRect(430, 140, 133, 20))
        self.waterid.setObjectName("waterid")
        self.line = QtWidgets.QFrame(CodeSet1)
        self.line.setGeometry(QtCore.QRect(310, 10, 16, 151))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.head = QtWidgets.QLineEdit(CodeSet1)
        self.head.setGeometry(QtCore.QRect(21, 180, 133, 20))
        self.head.setText("")
        self.head.setObjectName("head")
        self.label_10 = QtWidgets.QLabel(CodeSet1)
        self.label_10.setGeometry(QtCore.QRect(160, 180, 41, 16))
        self.label_10.setObjectName("label_10")
        self.wei = QtWidgets.QLineEdit(CodeSet1)
        self.wei.setGeometry(QtCore.QRect(431, 180, 133, 20))
        self.wei.setText("")
        self.wei.setReadOnly(True)
        self.wei.setObjectName("wei")
        self.label_11 = QtWidgets.QLabel(CodeSet1)
        self.label_11.setGeometry(QtCore.QRect(570, 180, 111, 16))
        self.label_11.setObjectName("label_11")

        self.retranslateUi(CodeSet1)
        QtCore.QMetaObject.connectSlotsByName(CodeSet1)

    def retranslateUi(self, CodeSet1):
        _translate = QtCore.QCoreApplication.translate
        CodeSet1.setWindowTitle(_translate("CodeSet1", "二维码配置"))
        self.label_9.setText(_translate("CodeSet1", "操作员"))
        self.label_15.setText(_translate("CodeSet1", "穴号2位"))
        self.label_8.setText(_translate("CodeSet1", "数量"))
        self.label_3.setText(_translate("CodeSet1", "日期"))
        self.label_5.setText(_translate("CodeSet1", "品名"))
        self.label_12.setText(_translate("CodeSet1", "工单号"))
        self.label_13.setText(_translate("CodeSet1", "料号"))
        self.label_14.setText(_translate("CodeSet1", "模号2位"))
        self.label_19.setText(_translate("CodeSet1", "深圳通达外箱条码序列预览"))
        self.cunchu.setText(_translate("CodeSet1", "保存配置"))
        self.label_18.setText(_translate("CodeSet1", "机型"))
        self.label_16.setText(_translate("CodeSet1", "流水号（测试）"))
        self.label_10.setText(_translate("CodeSet1", "前缀"))
        self.label_11.setText(_translate("CodeSet1", "条码位数"))

import style_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CodeSet1 = QtWidgets.QWidget()
    ui = Ui_CodeSet1()
    ui.setupUi(CodeSet1)
    CodeSet1.show()
    sys.exit(app.exec_())

