# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\DartCodeII\OutProt.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OutProt(object):
    def setupUi(self, OutProt):
        OutProt.setObjectName("OutProt")
        OutProt.setWindowModality(QtCore.Qt.ApplicationModal)
        OutProt.setEnabled(True)
        OutProt.resize(1200, 600)
        OutProt.setMinimumSize(QtCore.QSize(1200, 600))
        OutProt.setMaximumSize(QtCore.QSize(1200, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        OutProt.setWindowIcon(icon)
        OutProt.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(OutProt)
        self.label.setGeometry(QtCore.QRect(0, 0, 1201, 70))
        self.label.setAcceptDrops(False)
        self.label.setStyleSheet("background:#188eee;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.bulkprint = QtWidgets.QPushButton(OutProt)
        self.bulkprint.setGeometry(QtCore.QRect(1070, 540, 111, 41))
        self.bulkprint.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bulkprint.setStyleSheet("border:none;\n"
"background:#FFCD43;\n"
"color:#FFF;\n"
"font-size:14px;")
        self.bulkprint.setObjectName("bulkprint")
        self.comboBox = QtWidgets.QComboBox(OutProt)
        self.comboBox.setGeometry(QtCore.QRect(830, 540, 101, 41))
        self.comboBox.setObjectName("comboBox")
        self.choosurl = QtWidgets.QPushButton(OutProt)
        self.choosurl.setGeometry(QtCore.QRect(950, 540, 111, 40))
        self.choosurl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.choosurl.setStyleSheet("border:none;\n"
"background:#188eee;\n"
"color:#FFFFFF;\n"
"font-size:14px;")
        self.choosurl.setObjectName("choosurl")
        self.shuaxin = QtWidgets.QPushButton(OutProt)
        self.shuaxin.setGeometry(QtCore.QRect(1140, 15, 40, 40))
        self.shuaxin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.shuaxin.setStyleSheet("border:none;\n"
"background:#188eee;\n"
"color:#FFFFFF;")
        self.shuaxin.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/image/shuaxin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shuaxin.setIcon(icon1)
        self.shuaxin.setIconSize(QtCore.QSize(30, 30))
        self.shuaxin.setObjectName("shuaxin")
        self.outcode = QtWidgets.QLineEdit(OutProt)
        self.outcode.setGeometry(QtCore.QRect(20, 490, 701, 40))
        self.outcode.setStyleSheet("padding-left:10px;\n"
"font-size:16px;\n"
"font: 75 18pt \"AngsanaUPC\";")
        self.outcode.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.outcode.setObjectName("outcode")
        self.gudingno = QtWidgets.QLineEdit(OutProt)
        self.gudingno.setGeometry(QtCore.QRect(90, 440, 100, 30))
        self.gudingno.setStyleSheet("padding-left:10px;\n"
"font-size:14px;\n"
"")
        self.gudingno.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.gudingno.setReadOnly(False)
        self.gudingno.setObjectName("gudingno")
        self.label_2 = QtWidgets.QLabel(OutProt)
        self.label_2.setGeometry(QtCore.QRect(20, 450, 71, 21))
        self.label_2.setStyleSheet("font-size:16px;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(OutProt)
        self.label_3.setGeometry(QtCore.QRect(378, 450, 51, 21))
        self.label_3.setStyleSheet("font-size:16px;")
        self.label_3.setObjectName("label_3")
        self.pihaono = QtWidgets.QLineEdit(OutProt)
        self.pihaono.setGeometry(QtCore.QRect(430, 440, 100, 30))
        self.pihaono.setStyleSheet("padding-left:10px;\n"
"font-size:14px;\n"
"")
        self.pihaono.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.pihaono.setReadOnly(True)
        self.pihaono.setObjectName("pihaono")
        self.label_4 = QtWidgets.QLabel(OutProt)
        self.label_4.setGeometry(QtCore.QRect(541, 450, 51, 21))
        self.label_4.setStyleSheet("font-size:16px;")
        self.label_4.setObjectName("label_4")
        self.zhoubieno = QtWidgets.QLineEdit(OutProt)
        self.zhoubieno.setGeometry(QtCore.QRect(580, 440, 100, 30))
        self.zhoubieno.setStyleSheet("padding-left:10px;\n"
"font-size:14px;\n"
"")
        self.zhoubieno.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.zhoubieno.setReadOnly(True)
        self.zhoubieno.setObjectName("zhoubieno")
        self.label_5 = QtWidgets.QLabel(OutProt)
        self.label_5.setGeometry(QtCore.QRect(680, 410, 31, 21))
        self.label_5.setStyleSheet("font-size:16px;")
        self.label_5.setObjectName("label_5")
        self.banbenno = QtWidgets.QLineEdit(OutProt)
        self.banbenno.setGeometry(QtCore.QRect(720, 400, 100, 30))
        self.banbenno.setStyleSheet("padding-left:10px;\n"
"font-size:14px;\n"
"")
        self.banbenno.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.banbenno.setReadOnly(True)
        self.banbenno.setObjectName("banbenno")
        self.label_6 = QtWidgets.QLabel(OutProt)
        self.label_6.setGeometry(QtCore.QRect(830, 410, 71, 21))
        self.label_6.setStyleSheet("font-size:16px;")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(OutProt)
        self.label_7.setGeometry(QtCore.QRect(692, 450, 51, 21))
        self.label_7.setStyleSheet("font-size:16px;")
        self.label_7.setObjectName("label_7")
        self.yuanchanno = QtWidgets.QLineEdit(OutProt)
        self.yuanchanno.setGeometry(QtCore.QRect(750, 440, 100, 30))
        self.yuanchanno.setStyleSheet("padding-left:10px;\n"
"font-size:14px;\n"
"")
        self.yuanchanno.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.yuanchanno.setText("")
        self.yuanchanno.setReadOnly(True)
        self.yuanchanno.setObjectName("yuanchanno")
        self.label_9 = QtWidgets.QLabel(OutProt)
        self.label_9.setGeometry(QtCore.QRect(20, 410, 71, 21))
        self.label_9.setStyleSheet("font-size:16px;")
        self.label_9.setObjectName("label_9")
        self.metaid = QtWidgets.QLineEdit(OutProt)
        self.metaid.setGeometry(QtCore.QRect(90, 400, 100, 30))
        self.metaid.setStyleSheet("padding-left:10px;\n"
"font-size:14px;\n"
"")
        self.metaid.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.metaid.setText("")
        self.metaid.setReadOnly(True)
        self.metaid.setObjectName("metaid")
        self.meixiangno = QtWidgets.QLineEdit(OutProt)
        self.meixiangno.setGeometry(QtCore.QRect(270, 400, 100, 30))
        self.meixiangno.setStyleSheet("padding-left:10px;\n"
"font-size:14px;\n"
"")
        self.meixiangno.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.meixiangno.setText("")
        self.meixiangno.setReadOnly(True)
        self.meixiangno.setObjectName("meixiangno")
        self.label_10 = QtWidgets.QLabel(OutProt)
        self.label_10.setGeometry(QtCore.QRect(200, 410, 71, 21))
        self.label_10.setStyleSheet("font-size:16px;")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(OutProt)
        self.label_11.setGeometry(QtCore.QRect(380, 410, 41, 21))
        self.label_11.setStyleSheet("font-size:16px;")
        self.label_11.setObjectName("label_11")
        self.mode = QtWidgets.QLineEdit(OutProt)
        self.mode.setGeometry(QtCore.QRect(420, 400, 100, 30))
        self.mode.setStyleSheet("padding-left:10px;\n"
"font-size:14px;\n"
"")
        self.mode.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.mode.setText("")
        self.mode.setReadOnly(True)
        self.mode.setObjectName("mode")
        self.hole = QtWidgets.QLineEdit(OutProt)
        self.hole.setGeometry(QtCore.QRect(570, 400, 100, 30))
        self.hole.setStyleSheet("padding-left:10px;\n"
"font-size:14px;\n"
"")
        self.hole.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.hole.setText("")
        self.hole.setReadOnly(True)
        self.hole.setObjectName("hole")
        self.label_12 = QtWidgets.QLabel(OutProt)
        self.label_12.setGeometry(QtCore.QRect(530, 410, 71, 21))
        self.label_12.setStyleSheet("font-size:16px;")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(OutProt)
        self.label_13.setGeometry(QtCore.QRect(200, 450, 71, 21))
        self.label_13.setStyleSheet("font-size:16px;")
        self.label_13.setObjectName("label_13")
        self.liushuino = QtWidgets.QLineEdit(OutProt)
        self.liushuino.setGeometry(QtCore.QRect(918, 440, 100, 30))
        self.liushuino.setStyleSheet("padding-left:10px;\n"
"font-size:14px;\n"
"")
        self.liushuino.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.liushuino.setText("")
        self.liushuino.setReadOnly(True)
        self.liushuino.setObjectName("liushuino")
        self.label_14 = QtWidgets.QLabel(OutProt)
        self.label_14.setGeometry(QtCore.QRect(860, 450, 51, 21))
        self.label_14.setStyleSheet("font-size:16px;")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(OutProt)
        self.label_15.setGeometry(QtCore.QRect(1010, 410, 71, 21))
        self.label_15.setStyleSheet("font-size:16px;")
        self.label_15.setObjectName("label_15")
        self.pin = QtWidgets.QLineEdit(OutProt)
        self.pin.setGeometry(QtCore.QRect(1080, 400, 100, 30))
        self.pin.setStyleSheet("padding-left:10px;\n"
"font-size:14px;\n"
"")
        self.pin.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.pin.setObjectName("pin")
        self.dateEdit = QtWidgets.QDateEdit(OutProt)
        self.dateEdit.setGeometry(QtCore.QRect(270, 450, 101, 22))
        self.dateEdit.setStyleSheet("background:#ddd;")
        self.dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit.setObjectName("dateEdit")
        self.tip = QtWidgets.QLabel(OutProt)
        self.tip.setGeometry(QtCore.QRect(740, 500, 101, 21))
        self.tip.setStyleSheet("font-size:16px;")
        self.tip.setObjectName("tip")
        self.outproduct = QtWidgets.QLabel(OutProt)
        self.outproduct.setGeometry(QtCore.QRect(70, 550, 651, 21))
        self.outproduct.setStyleSheet("font-size:16px;")
        self.outproduct.setText("")
        self.outproduct.setObjectName("outproduct")
        self.tip_2 = QtWidgets.QLabel(OutProt)
        self.tip_2.setGeometry(QtCore.QRect(20, 550, 41, 21))
        self.tip_2.setStyleSheet("font-size:16px;")
        self.tip_2.setObjectName("tip_2")
        self.tip_3 = QtWidgets.QLabel(OutProt)
        self.tip_3.setGeometry(QtCore.QRect(740, 550, 31, 21))
        self.tip_3.setStyleSheet("font-size:16px;")
        self.tip_3.setObjectName("tip_3")
        self.tip_4 = QtWidgets.QLabel(OutProt)
        self.tip_4.setGeometry(QtCore.QRect(780, 550, 41, 21))
        self.tip_4.setStyleSheet("font-size:16px;")
        self.tip_4.setObjectName("tip_4")
        self.codelist = QtWidgets.QTableWidget(OutProt)
        self.codelist.setGeometry(QtCore.QRect(20, 90, 1161, 301))
        self.codelist.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.codelist.setObjectName("codelist")
        self.codelist.setColumnCount(0)
        self.codelist.setRowCount(0)
        self.tab5 = QtWidgets.QPushButton(OutProt)
        self.tab5.setGeometry(QtCore.QRect(800, 0, 90, 70))
        self.tab5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tab5.setStyleSheet("border:none;\n"
"background:#188EEE;\n"
"color:#FFFFFF;\n"
"font-size:16px;")
        self.tab5.setObjectName("tab5")
        self.tab3 = QtWidgets.QPushButton(OutProt)
        self.tab3.setGeometry(QtCore.QRect(580, 0, 90, 70))
        self.tab3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tab3.setStyleSheet("border:none;\n"
"background:#188EEE;\n"
"color:#FFFFFF;\n"
"font-size:16px;")
        self.tab3.setObjectName("tab3")
        self.tab4 = QtWidgets.QPushButton(OutProt)
        self.tab4.setGeometry(QtCore.QRect(670, 0, 131, 70))
        self.tab4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tab4.setStyleSheet("border:none;\n"
"background:#349BFF;\n"
"color:#FFFFFF;\n"
"font-size:16px;")
        self.tab4.setObjectName("tab4")
        self.tab2 = QtWidgets.QPushButton(OutProt)
        self.tab2.setGeometry(QtCore.QRect(440, 0, 140, 70))
        self.tab2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tab2.setStyleSheet("border:none;\n"
"background:#188EEE;\n"
"color:#FFFFFF;\n"
"font-size:16px;")
        self.tab2.setObjectName("tab2")
        self.tab1 = QtWidgets.QPushButton(OutProt)
        self.tab1.setGeometry(QtCore.QRect(300, 0, 140, 70))
        self.tab1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tab1.setStyleSheet("border:none;\n"
"background:#188EEE;\n"
"color:#FFFFFF;\n"
"font-size:16px;")
        self.tab1.setObjectName("tab1")
        self.chanpinno = QtWidgets.QComboBox(OutProt)
        self.chanpinno.setGeometry(QtCore.QRect(900, 400, 101, 30))
        self.chanpinno.setObjectName("chanpinno")
        self.created = QtWidgets.QPushButton(OutProt)
        self.created.setGeometry(QtCore.QRect(1070, 490, 111, 40))
        self.created.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.created.setStyleSheet("border:none;\n"
"background:#188eee;\n"
"color:#FFFFFF;\n"
"font-size:14px;")
        self.created.setObjectName("created")
        self.label.raise_()
        self.bulkprint.raise_()
        self.comboBox.raise_()
        self.choosurl.raise_()
        self.shuaxin.raise_()
        self.outcode.raise_()
        self.label_2.raise_()
        self.gudingno.raise_()
        self.label_3.raise_()
        self.pihaono.raise_()
        self.label_4.raise_()
        self.zhoubieno.raise_()
        self.label_5.raise_()
        self.banbenno.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.yuanchanno.raise_()
        self.label_9.raise_()
        self.metaid.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.mode.raise_()
        self.meixiangno.raise_()
        self.label_12.raise_()
        self.hole.raise_()
        self.label_13.raise_()
        self.liushuino.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.pin.raise_()
        self.dateEdit.raise_()
        self.tip.raise_()
        self.outproduct.raise_()
        self.tip_2.raise_()
        self.tip_3.raise_()
        self.tip_4.raise_()
        self.codelist.raise_()
        self.tab5.raise_()
        self.tab3.raise_()
        self.tab4.raise_()
        self.tab2.raise_()
        self.tab1.raise_()
        self.chanpinno.raise_()
        self.created.raise_()

        self.retranslateUi(OutProt)
        QtCore.QMetaObject.connectSlotsByName(OutProt)

    def retranslateUi(self, OutProt):
        _translate = QtCore.QCoreApplication.translate
        OutProt.setWindowTitle(_translate("OutProt", "扫描工具v2"))
        self.bulkprint.setText(_translate("OutProt", "打印条码"))
        self.choosurl.setText(_translate("OutProt", "选择模板目录"))
        self.outcode.setPlaceholderText(_translate("OutProt", "请输入外箱条码"))
        self.gudingno.setPlaceholderText(_translate("OutProt", "固定编码"))
        self.label_2.setText(_translate("OutProt", "固定编码"))
        self.label_3.setText(_translate("OutProt", "批次号"))
        self.pihaono.setPlaceholderText(_translate("OutProt", "批次号"))
        self.label_4.setText(_translate("OutProt", "周别"))
        self.zhoubieno.setPlaceholderText(_translate("OutProt", "周别"))
        self.label_5.setText(_translate("OutProt", "版本"))
        self.banbenno.setPlaceholderText(_translate("OutProt", "版本"))
        self.label_6.setText(_translate("OutProt", "产品名称"))
        self.label_7.setText(_translate("OutProt", "原产地"))
        self.yuanchanno.setPlaceholderText(_translate("OutProt", "原产地"))
        self.label_9.setText(_translate("OutProt", "客户料号"))
        self.metaid.setPlaceholderText(_translate("OutProt", "客户料号"))
        self.meixiangno.setPlaceholderText(_translate("OutProt", "每箱数量"))
        self.label_10.setText(_translate("OutProt", "每箱数量"))
        self.label_11.setText(_translate("OutProt", "模号"))
        self.mode.setPlaceholderText(_translate("OutProt", "模号"))
        self.hole.setPlaceholderText(_translate("OutProt", "穴号"))
        self.label_12.setText(_translate("OutProt", "穴号"))
        self.label_13.setText(_translate("OutProt", "有效日期"))
        self.liushuino.setPlaceholderText(_translate("OutProt", "流水号"))
        self.label_14.setText(_translate("OutProt", "流水号"))
        self.label_15.setText(_translate("OutProt", "产品代号"))
        self.pin.setText(_translate("OutProt", "0"))
        self.pin.setPlaceholderText(_translate("OutProt", "产品代号"))
        self.dateEdit.setDisplayFormat(_translate("OutProt", "yyyy-M-d"))
        self.tip.setText(_translate("OutProt", "外箱条码"))
        self.tip_2.setText(_translate("OutProt", "预览："))
        self.tip_3.setText(_translate("OutProt", "长度"))
        self.tip_4.setText(_translate("OutProt", "0"))
        self.tab5.setText(_translate("OutProt", "出货扫描"))
        self.tab3.setText(_translate("OutProt", "出库扫描"))
        self.tab4.setText(_translate("OutProt", "打印出货标签"))
        self.tab2.setText(_translate("OutProt", "外箱条码管理"))
        self.tab1.setText(_translate("OutProt", "产品条码管理"))
        self.created.setText(_translate("OutProt", "生成"))

import style_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OutProt = QtWidgets.QWidget()
    ui = Ui_OutProt()
    ui.setupUi(OutProt)
    OutProt.show()
    sys.exit(app.exec_())

